
services:
  app:
    image: 'hotel'
    build:
      context: .
    ports:
      - "8082:8082"
    container_name: hotelapp
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=akilan24
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: hoteldb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=akilan24